DOMAIN = "metlink_nz"

CONF_STOPS = "stops"
CONF_STOP_ID = "stop_id"
CONF_DEST = "destination"
CONF_ROUTE = "route"
CONF_NUM_DEPARTURES = "num_departures"

ATTR_ACCESSIBLE = "wheelchair_accessible"
ATTR_AIMED = "aimed"
ATTR_ARRIVAL = "arrival"
ATTR_CLOSED = "closed"
ATTR_DELAY = "delay"
ATTR_DEPARTURE = "departure"
ATTR_DEPARTURES = "departures"
ATTR_DESTINATION = "destination"
ATTR_DIRECTION = "direction"
ATTR_EXPECTED = "expected"
ATTR_FAREZONE = "farezone"
ATTR_MONITORED = "monitored"
ATTR_NAME = "name"
ATTR_OPERATOR = "operator"
ATTR_ORIGIN = "origin"
ATTR_STOP = "stop_id"
ATTR_SERVICE = "service_id"
ATTR_STATUS = "status"
ATTR_VEHICLE = "vehicle_id"
